### ISSUE TITLE
Handle concurrent access

### ISSUE THREAD

**Issue by XCarrel** [CPNV-ES/runners#62]
_From @XCarrel on August 13, 2018 12:13_

Implement proper concurrent access management: two drivers open a run to take it, the first to take action 'wins', the other is properly notified 

_Copied from original issue: XCarrel/pruns#5_

**Comment by AlexandreJunod** [comment]
The backlog already watches in the request the value of "updated_at" and does the necessary to allow or disallow to take a run.

Don't forget to add "updated_at" to the values returned.

Actually it's working on postman, if the updated_at differs, there's a text returned saying "Le run à été modifié entre temps, veuillez recharger le run". Tell me if you need to change the text/value returned.
